{
    'name': 'Meliora Gym',
    'version': '1.0',
    'summary': 'Gym Application',
    'author': 'CarendaA',
    'category': 'Services',
    'depends': ['base', 'mail', 'website' , 'portal'],
    'data': [
        'views/gym_menu_views.xml',
        'views/gym_member_views.xml',
        'security/ir.model.access.csv',
        'views/gym_membership_plan_views.xml',
        'views/gym_trainer_views.xml',
        'views/gym_session_views.xml',
        'views/gym_class_attendance_views.xml',
        'views/gym_payment_views.xml',
        'views/gym_class_type_views.xml',
        'views/gym_dashboard_views.xml',
        'views/gym_dashboard_kanban.xml',
        'views/gym_portal_templates.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'views/gym_dashboard_templates.xml',
    ],
    'qweb': [
    ],
    'installable': True,
    'application': True,
}
