from . import gym_member
from . import gym_membership_plan
from . import gym_trainer
from . import gym_session
from . import gym_class_attendance
from . import gym_payment
from . import gym_class_type
from . import gym_dashboard
from . import ext_res_partners
from . import gym_workout_tip
from . import gym_feed_message